# Generated by Django 5.2.17 on 2026-09-24 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('index_status', models.CharField(choices=[('not_indexed', 'Not indexed'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_indexed', max_length=16)),
                ('index_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='businesses.business')),
            ],
            options={
                'ordering': ['business', 'question', 'id'],
                'constraints': [models.UniqueConstraint(fields=('business', 'question', 'answer'), name='unique_business_question_answer')],
            },
        ),
    ]
