# Generated by Django 5.2.17 on 2026-09-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_knowledgeitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeitem',
            options={'ordering': ['business', 'question', 'id'], 'verbose_name': 'Q&A', 'verbose_name_plural': 'Q&A'},
        ),
    ]
