# Generated by Django 5.2.17 on 2026-09-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("businesses", "0003_alter_knowledgeitem_options")]

    operations = [
        migrations.RemoveConstraint(
            model_name="knowledgeitem",
            name="unique_business_question_answer",
        ),
        migrations.AddField(
            model_name="knowledgeitem",
            name="replacement_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replacement_drafts",
                to="businesses.knowledgeitem",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgeitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("replacement_for__isnull", True)),
                fields=("business", "question", "answer"),
                name="unique_business_question_answer",
            ),
        ),
    ]
