# Generated by Django 5.2.17 on 2026-09-24 08:15

from django.db import migrations, models


def set_existing_vector_ids(apps, schema_editor):
    KnowledgeItem = apps.get_model("businesses", "KnowledgeItem")
    for item in KnowledgeItem.objects.filter(vector_id__isnull=True).iterator():
        item.vector_id = item.id
        item.save(update_fields=["vector_id"])


class Migration(migrations.Migration):
    dependencies = [("businesses", "0004_remove_knowledgeitem_unique_business_question_answer_and_more")]

    operations = [
        migrations.AddField(
            model_name="knowledgeitem",
            name="vector_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(set_existing_vector_ids, migrations.RunPython.noop),
    ]
