# Generated by Django 5.2.17 on 2026-09-29 04:56

import businesses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("businesses", "0005_knowledgeitem_vector_id")]

    operations = [
        migrations.CreateModel(
            name="BusinessIntegration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("embed_token", models.CharField(default=businesses.models._new_embed_token, max_length=64, unique=True)),
                ("allowed_origins", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="integration", to="businesses.business")),
            ],
        ),
        migrations.CreateModel(
            name="BusinessApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secret_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("integration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="api_keys", to="businesses.businessintegration")),
            ],
        ),
    ]
