# Generated by Django 5.2.17 on 2026-10-04 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businessintegration_businessapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('product', models.CharField(blank=True, max_length=120)),
                ('version', models.CharField(blank=True, max_length=120)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('index_status', models.CharField(choices=[('not_indexed', 'Not indexed'), ('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_indexed', max_length=16)),
                ('index_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='businesses.document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['document__business__name', 'title', 'revision_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'revision_number'), name='unique_document_revision_number'), models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('document',), name='one_document_draft'), models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('document',), name='one_document_published')],
            },
        ),
    ]
