# Generated by Django 5.2.17 on 2026-10-04 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_document_documentrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('heading', models.TextField(blank=True)),
                ('text', models.TextField()),
                ('vector_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('index_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='businesses.documentrevision')),
            ],
            options={
                'ordering': ['revision', 'order'],
                'constraints': [models.UniqueConstraint(fields=('revision', 'order'), name='unique_document_chunk_order')],
            },
        ),
    ]
