# Generated by Django 5.2.17 on 2026-10-05 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0008_documentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrevision',
            name='index_status',
            field=models.CharField(choices=[('not_indexed', 'Not indexed'), ('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='not_indexed', max_length=16),
        ),
        migrations.CreateModel(
            name='DocumentIndexAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('interrupted', 'Interrupted')], default='running', max_length=16)),
                ('owner_id', models.CharField(max_length=64)),
                ('chunks_total', models.PositiveIntegerField(default=0)),
                ('chunks_completed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_expires_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_attempts', to='businesses.documentrevision')),
            ],
            options={
                'ordering': ['-started_at', 'id'],
            },
        ),
    ]
